### PR TITLE
style: :art: Updated icon to be the same as the devtoys logo

### PR DESCRIPTION
**Pull request by KillDozerX2**
This will make it identyfiable in the sidebar instead of just using a generic tools icon
This is what it looks like
Screenshot 2022-02-21 at 7 47 39 PM

### CODE REVIEW

**Comment by KeJunMao** [comment]
Wow, it's a great icon, but the width of the line doesn't match the icon of vscode. Can you try to make it match better

**Comment by KillDozerX2** [comment]
Sure, which line are you talking about btw?

**Comment by KillDozerX2** [comment]
Done, now it's more consistent
Screenshot 2022-02-21 at 9 10 16 PM

**Comment by KeJunMao** [comment]
nice job! thank you again

**Pull request merged**
